/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar_time.c"
#include "dmenu_logout.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_statuscolors.c"
#include "bar_tags.c"

/* Other patches */
#include "attachx.c"
#include "cyclelayouts.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "mpdcontrol.c"
#include "moveresize.c"
#include "placemouse.c"
#include "roundedcorners.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "transfer.c"
#include "vanitygaps.c"
/* Layouts */
#include "layout_flextile-deluxe.c"
#include "layout_grid.c"

